matches = [
    {
        "match": 1,
        "champion": "Yasuo",
        "kills": 8,
        "deaths": 5,
        "assists": 6,
        "cs": 210,
        "game_minutes": 32,
        "vision_score": 18,
        "win": True,
    },
    {
        "match": 2,
        "champion": "Zed",
        "kills": 0,
        "deaths": 6,
        "assists": 3,
        "cs": 110,
        "game_minutes": 35,
        "vision_score": 18,
        "win": False,
    },
    {
        "match": 3,
        "champion": "Annie",
        "kills": 5,
        "deaths": 0,
        "assists": 1,
        "cs": 210,
        "game_minutes": 23,
        "vision_score": 20,
        "win": True,
    },
]